language: node_js
node_js:
  - 0.12.4
sudo: false
after_success:
  - npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: f061......1f4e
    secure: DTx6RpbTDeM8sEoBHR+Lr4g4UIRIv8uoZzxF+ahQFtlNoFNw6/MupU2i0q2E71r/f+EaR84fJEy+DPposjbzo2ubkkEdaTqTIkVMwAjRcTl07yd+RzyX1KKSWVF8e9X/aYjUmc/AMjE3wQyjgK8c2vm6Q4hwAGUmnLajNRIOOnraV9Rw7j/NrF+CuNfiG1I76OQTyDMbtAceAcDxP2Bt+a7iOcVjACQvDUDTtolNTzMvzwHTVMLYwZLplgauRTs8PddvgdqDkkVVSUq3zouvYpuMfNepJvKJFq/3NvMSezmW5dTF8gcpFGWAgqJGKdEbFXgBhVxGKVXrYb21OypfrzXcxUCRo1h4C+0EWbvs3TZjE1uaAkiFKU7uP9KudMTP8NAkJcKKaY52qvGpiwRC4mj3Cb9NPEQy5Evs6/2cdEJ3r8Y4h6eMzP5v+12Ko2v/Nk/a2ur6P+PeLgg3ke0kbiE1Em4K8uG+5Q/dlKsUJMiX9NxSmR4bRckyEDhuK99z3FRCeETtopb5usd2qppS3haduIoKxtaSoehoz1Pdk+XRidLGDAm/Y+pQhCXAh8qbI8e1NFTRkIOXI5X97d8k4OaP19T2Rf8p6y/SS5H190DqlRkwBwOra83SFIVGXuRxWtvCD7prmVdgs0T5dlJN1Okc48YMxp517PN9sZvni1Q=
  on:
    tags: true
    repo: Brightspace/frau-superagent-xsrf-token
